### ISSUE TITLE
[BUG] MinGW test errors: A required privilege is not held by the client.

### ISSUE THREAD

**Issue by SamuelMarks** [sharkdp/fd#1324]
### Checks

- [X] I have read the troubleshooting section and still think this is a bug.

### Describe the bug you encountered:

thread 'test_type_empty' panicked at 'working directory: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }', tests\testenv\mod.rs:159:69

```
---- test_symlink_and_full_path stdout ----
thread 'test_symlink_and_full_path' panicked at 'working directory: Os { code: 1314, kind: Uncategorized, message: "A required privilege is not held by the client." }', tests\testenv\mod.rs:159:69
stack backtrace:
```

### Describe what you expected to happen:

No error. FYI: No issue with the produced binary, it works as advertised. Just the tests don't work.

### What version of `fd` are you using?

0d32bebcc2ff9ca01d2fc8410e6659913ed7212d

### Which operating system / distribution are you on?

```shell
MINGW64 /tmp/fd
$ rustc --version
-bash: $'\302\203rustc': command not found

MINGW64 /tmp/fd
$(which rustc) --version
rustc 1.69.0 (84c898d65 2023-04-16) (Rev1, Built by MSYS2 project)
```
```

**Comment by tavianator** [comment]
What version of Windows do you have?  On new enough versions I unprivileged users are allowed to create symlinks: https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/

**Comment by SamuelMarks** [comment]
@tavianator Windows 11 (22621.1778)
